{{- define "clickhouseSecret" }}
apiVersion: v1
kind: Secret
metadata:
  {{- if (and .Values.testFlags .Values.testFlags.legacyNames) }}
  name: clickhouse-login
  {{- else }}
  name: {{ include "name" (dict "Release" .Release "name" `clickhouse` .nameOverride .Values.clickhouse.nameOverride) }}-login
  {{- end }}
  namespace: {{ include "ns" (dict "Values" .Values "Release" .Release "IndividualNamespace" .targetNamespace) }}
type: Opaque
data:
  {{- if .Values.clickhouse.external.enabled }}
  password: {{ .Values.clickhouse.external.connection.password | b64enc | quote }}
  username: {{ .Values.clickhouse.external.connection.username | b64enc | quote }}
  {{- else }}
  password: {{ .Values.clickhouse.internal.password | b64enc | quote }}
  username: {{ .Values.clickhouse.internal.username | b64enc | quote }}
  {{- end }}
{{- end }}