{{- define "ipinfoProviderSecret" }}
apiVersion: v1
kind: Secret
metadata:
  {{- if (and .Values.testFlags .Values.testFlags.legacyNames) }}
  name: ipinfo-config-{{ .key }}
  {{- else }}
  name: {{ include "name" (dict "Release" .Release "name" (printf "ipinfo-config-%s" .key)) }}
  {{- end }}
  namespace: {{ include "ns" (dict "Values" .Values "Release" .Release "IndividualNamespace" .targetNamespace) }}
type: Opaque
data:
  ipinfo.yaml: {{ include "ipinfoProviderObject" (dict "Values" .Values "key" .key) | b64enc | quote }}
{{- end }}