{{- define "loggingEnvs" }}
{{- if eq .level "panic" }}
- name: APP_LOG_LEVEL
  value: '0'
{{ else if eq .level "fatal" }}
- name: APP_LOG_LEVEL
  value: '1'
{{ else if eq .level "error" }}
- name: APP_LOG_LEVEL
  value: '2'
{{ else if eq .level "warning" }}
- name: APP_LOG_LEVEL
  value: '3'
{{ else if eq .level "info" }}
- name: APP_LOG_LEVEL
  value: '4'
{{ else if eq .level "debug" }}
- name: APP_LOG_LEVEL
  value: '5'
{{ else if eq .level "trace" }}
- name: APP_LOG_LEVEL
  value: '6'
{{- else }}
{{ fail "invalid log level, valid values are panic, fatal, error, warning, info, debug, trace" }}
{{- end }}
{{- end }}