{{- define "name" -}}
{{- if .nameOverride -}}
{{- .nameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name .name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}