{{- define "nudityDetectionProviderSecret" }}
apiVersion: v1
kind: Secret
metadata:
  {{- if (and .Values.testFlags .Values.testFlags.legacyNames) }}
  name: nuditydetection-config-{{ .key }}
  {{- else }}
  name: {{ include "name" (dict "Release" .Release "name" (printf "nuditydetection-config-%s" .key)) }}
  {{- end }}
  namespace: {{ include "ns" (dict "Values" .Values "Release" .Release "IndividualNamespace" .targetNamespace) }}
type: Opaque
data:
  nuditydetection.yaml: {{ include "nudityDetectionProviderObject" (dict "Values" .Values "Release" .Release "key" .key) | b64enc | quote }}
{{- end }}