{{- define "redisSecret" }}
{{- if .Values.redis.external.enabled }}
apiVersion: v1
kind: Secret
metadata:
  {{- if (and .Values.testFlags .Values.testFlags.legacyNames) }}
  name: redis-url
  {{- else }}
  name: {{ include "name" (dict "Release" .Release "name" "redis" "nameOverride" .Values.redis.nameOverride) }}-url
  {{- end }}
  namespace: {{ include "ns" (dict "Values" .Values "Release" .Release "IndividualNamespace" .targetNamespace) }}
type: Opaque
data:
  url: {{ required "Redis external URL must be specified" .Values.redis.external.url | b64enc | quote }}
{{- end }}
{{- end }}