{{- define "storageProviderSecret" }}
apiVersion: v1
kind: Secret
metadata:
  {{- if (and .Values.testFlags .Values.testFlags.legacyNames) }}
  name: storage-config-{{ .key }}
  {{- else }}
  name: {{ include "name" (dict "Release" .Release "name" (printf "storage-config-%s" .key)) }}
  {{- end }}
  namespace: {{ include "ns" (dict "Values" .Values "Release" .Release "IndividualNamespace" .targetNamespace) }}
type: Opaque
data:
  storage-{{ .key }}.yaml: {{ include "storageProviderObject" (dict "Values" .Values "Release" .Release "key" .key) | b64enc | quote }}
{{- end }}