{{ if .Values.categorizer.adminApp.enabled }}
{{ if .Values.categorizer.mirroring.enabled }}
---
#
# Define the cronjob.
#
{{- if semverCompare ">=1.21-0" .Capabilities.KubeVersion.Version }}
apiVersion: batch/v1
{{- else }}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ include "name" (dict "Release" .Release "name" "domain-mirror-sync" "nameOverride" .Values.categorizer.mirroring.nameOverride) }}
  namespace: {{ include "ns" (dict "Values" .Values "Release" .Release "IndividualNamespace" .Values.categorizer.namespace) }}
spec:
  schedule: {{ .Values.categorizer.mirroring.schedule }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            job: {{ include "name" (dict "Release" .Release "name" "domain-mirror-sync" "nameOverride" .Values.categorizer.mirroring.nameOverride) }}
        spec:
          imagePullSecrets:
          - name: {{ include "name" (dict "Release" .Release "name" "admin-app" "nameOverride" .Values.categorizer.adminApp.nameOverride) }}-gitlab-registry
          automountServiceAccountToken: false
          volumes:
          - name: cache-volume
            emptyDir: {}
          containers:
          - name: {{ include "name" (dict "Release" .Release "name" "domain-mirror-sync" "nameOverride" .Values.categorizer.mirroring.nameOverride) }}
            volumeMounts:
            - mountPath: /cache
              name: cache-volume
            image: {{ .Values.categorizer.mirroring.image }}
            resources:
              {{- toYaml .Values.categorizer.mirroring.resources | nindent 14 }}
            env:
            {{ include "dbEnvs" . | indent 12 }}
            {{ include "loggingEnvs" (dict "level" .Values.categorizer.mirroring.logLevel) | nindent 12 }}
            - name: APP_TIMEOUT
              value: {{ .Values.categorizer.mirroring.timeout }}
            - name: APP_BATCH_ADD_TIMEOUT
              value: {{ .Values.categorizer.mirroring.batchTimeout }}
            - name: APP_REMOTE_CATEGORIZER_BATCH_SIZE
              value: {{ .Values.categorizer.mirroring.batchSize | quote }}
            - name: APP_INTERNAL_BATCH_SIZE
              value: {{ .Values.categorizer.mirroring.internalBatchSize | quote }}
            - name: APP_REMOTE_CATEGORIZER_REQUEST_TIMEOUT
              value: {{ .Values.categorizer.mirroring.externalHTTPTimeout }}
            - name: APP_REMOTE_CATEGORIZER_MIN_WAIT
              value: {{ .Values.categorizer.mirroring.externalHttpMinWait }}
            - name: APP_CATEGORIZER_USERNAME
              value: {{ .Values.categorizer.mirroring.login.username }}
            - name: APP_DB_FILE
              value: /cache/events.db
          restartPolicy: Never
{{ end }}
{{ end }}