{{ if .Values.categorizer.adminApp.enabled }}
{{ if .Values.categorizer.ipMirroring.enabled }}
---
#
# Define the cronjob.
#
{{- if semverCompare ">=1.21-0" .Capabilities.KubeVersion.Version }}
apiVersion: batch/v1
{{- else }}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ include "name" (dict "Release" .Release "name" "ip-mirror-sync" "nameOverride" .Values.categorizer.ipMirroring.nameOverride) }}
  namespace: {{ include "ns" (dict "Values" .Values "Release" .Release "IndividualNamespace" .Values.categorizer.namespace) }}
spec:
  schedule: {{ .Values.categorizer.ipMirroring.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            job: {{ include "name" (dict "Release" .Release "name" "ip-mirror-sync" "nameOverride" .Values.categorizer.ipMirroring.nameOverride) }}
        spec:
          imagePullSecrets:
          - name: {{ include "name" (dict "Release" .Release "name" "admin-app" "nameOverride" .Values.categorizer.adminApp.nameOverride) }}-gitlab-registry
          automountServiceAccountToken: false
          containers:
          - name: {{ include "name" (dict "Release" .Release "name" "ip-mirror-sync" "nameOverride" .Values.categorizer.ipMirroring.nameOverride) }}
            image: {{ .Values.categorizer.ipMirroring.image }}
            resources:
              {{- toYaml .Values.categorizer.ipMirroring.resources | nindent 14 }}
            env:
            #
            # DB Connection
            #
            {{ include "dbEnvs" . | indent 12 }}
            - name: APP_PG_MAX_IDLE_CONNS
              value: {{ .Values.categorizer.ipMirroring.maxIdleConns | int | quote }}
            - name: APP_PG_MAX_OPEN_CONNS
              value: {{ .Values.categorizer.ipMirroring.maxOpenConns | int | quote }}
            - name: APP_EXTERNAL_HTTP_TIMEOUT
              value: {{ .Values.categorizer.ipMirroring.externalHTTPTimeout }}
            - name: APP_INTERNAL_HTTP_TIMEOUT
              value: {{ .Values.categorizer.ipMirroring.internalHTTPTimeout }}
            - name: APP_CATEGORIZER_HOST
              value: {{ include "name" (dict "Release" .Release "name" "admin-app" "nameOverride" .Values.categorizer.adminApp.nameOverride) }}.{{ include "ns" (dict "Values" .Values "Release" .Release "IndividualNamespace" .Values.categorizer.namespace) }}.svc.cluster.local:{{ .Values.categorizer.adminApp.svcPort }}
            - name: APP_CATEGORIZER_USERNAME
              value: {{ .Values.categorizer.ipMirroring.login.username }}
            - name: APP_CATEGORIZER_PASSWORD
              value: {{ required "Need a categorizer password" .Values.categorizer.ipMirroring.login.accessKey }}
          restartPolicy: Never
{{ end }}
{{ end }}