{{- if (or .Values.clickhouse.external.enabled .Values.clickhouse.internal.enabled) }}
{{- if (and .Values.testFlags .Values.testFlags.legacyNames) }}
{{ include "clickhouseSecret" (dict "Values" .Values "Release" .Release "targetNamespace" .Values.clickhouse.namespace) }}
{{- end }}
{{- end }}