{{- if .Values.dns.enabled }}
{{- if .Values.dns.newDomainNotifier.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name" (dict "Release" .Release "name" "new-domain-notifier" "nameOverride" .Values.dns.newDomainNotifier.nameOverride) }}-categorizer
  namespace: {{ include "ns" (dict "Values" .Values "Release" .Release "IndividualNamespace" .Values.dns.namespace) }}
  labels:
    {{- include "safesurfer-dns.labels" . | nindent 4 }}
{{- if .Values.dns.labels }}
{{- with .Values.dns.labels }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
data:
  categorizer-access-key: {{ .Values.dns.newDomainNotifier.categorizer.key | toString | b64enc | quote }}
  categorizer-user: {{ .Values.dns.newDomainNotifier.categorizer.user | toString | b64enc | quote }}
{{- end }}
{{- end }}