#
# Cert and cluster issuer
#
{{- if .Values.dns.enabled }}
{{- if .Values.dns.dot.enabled }}
{{ include "cert" (dict "cert" .Values.dns.dot.tls "overrideLegacyName" "letsencrypt-prod-dot" "Release" .Release "name" (include "name" (dict "Release" .Release "name" "dot" "nameOverride" .Values.dns.dot.nameOverride)) "namespace" .Values.dns.namespace "preferredChain" "ISRG Root X1" "dnsNames" (list  (printf "*.%s" .Values.dns.dot.host) .Values.dns.dot.host) "Values" .Values) }}
{{- end }}
{{- end }}