{{- if .Values.dns.enabled }}
{{- if .Values.dns.dnscrypt.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name" (dict "Release" .Release "name" "dnscrypt" "nameOverride" .Values.dns.dnscrypt.nameOverride) }}-certs
  namespace: {{ include "ns" (dict "Values" .Values "Release" .Release "IndividualNamespace" .Values.dns.namespace) }}
type: Opaque
data:
  resolver.cert: {{ .Values.dns.dnscrypt.cert.certFile | b64enc | quote }}
  resolver.key: {{ .Values.dns.dnscrypt.cert.keyFile | b64enc | quote }}
{{- end }}
{{- end }}