{{- if .Values.dns.enabled }}
{{- if .Values.dns.dns.enabled }}
{{- if .Values.dns.dns.initContainers.initLmdb.backend.lmdbFeed.peering.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" (dict "Release" .Release "name" "init-lmdb" "nameOverride" .Values.dns.dns.initContainers.initLmdb.nameOverride) }}-peering
  namespace: {{ include "ns" (dict "Values" .Values "Release" .Release "IndividualNamespace" .Values.dns.namespace) }}
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: {{ .Values.dns.dns.initContainers.initLmdb.backend.lmdbFeed.peering.port }}
    protocol: TCP
    name: peering
  selector:
    {{- include "safesurfer-dns.selectorLabels" . | nindent 4 }}
    app: {{ include "dnsContainerAndAppName" . }}
    modelVersion: '1'
{{- end }}
{{- end }}
{{- end }}