#
# Cert and cluster issuer
#
{{- if .Values.dns.enabled }}
{{- if .Values.dns.doh.enabled }}
{{ $release := .Release }}
{{ $values := .Values }}
{{- range $idx, $cert := .Values.dns.doh.tls }}
{{ include "cert" (dict "cert" $cert "noHttpSupport" true "Release" $release "name" (include "name" (dict "Release" $release "name" (printf "doh-%s" $idx) "nameOverride" $values.dns.doh.nameOverride)) "namespace" $values.dns.namespace "Values" $values) }}
{{- end }}
{{- end }}
{{- end }}