{{- if .Values.dns.enabled }}
{{- if .Values.dns.dot.enabled }}
{{- if .Values.dns.dot.deployment }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" (dict "Release" .Release "name" "dot" "nameOverride" .Values.dns.dot.nameOverride) }}-tcp
  namespace: {{ include "ns" (dict "Values" .Values "Release" .Release "IndividualNamespace" .Values.dns.namespace) }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    {{- with .Values.dns.dot.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "safesurfer-dns.labels" . | nindent 4 }}
{{- if .Values.dns.labels }}
{{- with .Values.dns.labels }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
spec:
  ports:
  - name: "tcp-dns-dot"
    port: {{ .Values.dns.dot.service.port }}
    protocol: TCP
    targetPort: {{ .Values.dns.dot.bindPort }}
  type: {{ .Values.dns.dot.service.type }}
  {{- if (or (eq .Values.dns.dot.service.type "LoadBalancer") (eq .Values.dns.dot.service.type "NodePort")) }}
  externalTrafficPolicy: Local
  {{- if .Values.dns.dot.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.dns.dot.service.loadBalancerIP }}
  {{- end }}
  sessionAffinity: ClientIP
  {{- end }}
  externalIPs:
{{- if .Values.dns.dot.service.externalIPs }}
{{- with .Values.dns.dot.service.externalIPs }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
  selector:
    {{- include "safesurfer-dns.selectorLabels" . | nindent 4 }}
    app: {{ include "dotContainerAndAppName" . }}
{{- end }}
{{- end }}
{{- end }}