{{- if .Values.dns.enabled }}
{{- if (and .Values.testFlags .Values.testFlags.legacyNames) }}
#
# Secret for DB connection.
#
{{ include "dbSecret" (dict "Values" .Values "Release" .Release "targetNamespace" .Values.dns.namespace) }}
{{- end }}
{{- end }}