{{- if .Values.dns.enabled }}
{{- if .Values.dns.doh.enabled }}
{{- if .Values.dns.doh.deployment }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" (dict "Release" .Release "name" "doh" "nameOverride" .Values.dns.doh.nameOverride) }}
  namespace: {{ include "ns" (dict "Values" .Values "Release" .Release "IndividualNamespace" .Values.dns.namespace) }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    {{- if .Values.dns.doh.service.isGCPNEG }}
    cloud.google.com/neg: '{"exposed_ports": {"{{ .Values.dns.doh.service.port }}":{}}}'
    {{- end }}
    {{- with .Values.dns.doh.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "safesurfer-dns.labels" . | nindent 4 }}
{{- if .Values.dns.labels }}
{{- with .Values.dns.labels }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
spec:
  ports:
  - name: "tcp-dns-doh"
    port: {{ .Values.dns.doh.service.port }}
    protocol: TCP
    targetPort: {{ .Values.dns.doh.bindPort }}
  type: {{ .Values.dns.doh.service.type }}
  {{- if (or (eq .Values.dns.doh.service.type "LoadBalancer") (eq .Values.dns.doh.service.type "NodePort")) }}
  externalTrafficPolicy: Local
  {{- if .Values.dns.doh.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.dns.doh.service.loadBalancerIP }}
  {{- end }}
  sessionAffinity: ClientIP
  {{- end }}
  externalIPs:
{{- if .Values.dns.doh.service.externalIPs }}
{{- with .Values.dns.doh.service.externalIPs }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
  selector:
    {{- include "safesurfer-dns.selectorLabels" . | nindent 4 }}
    app: {{ include "dohContainerAndAppName" . }}
{{- end }}
{{- end }}
{{- end }}