{{- if .Values.dns.enabled }}
{{- if .Values.dns.dns.enabled }}
{{- if .Values.dns.dns.ipv6Service.tcp.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" (dict "Release" .Release "name" "dns-tcp-ipv6") }}
  namespace: {{ include "ns" (dict "Values" .Values "Release" .Release "IndividualNamespace" .Values.dns.namespace) }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    {{- with .Values.dns.dns.ipv6Service.tcp.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "safesurfer-dns.labels" . | nindent 4 }}
spec:
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv6
  type: {{ .Values.dns.dns.ipv6Service.tcp.type }}
  {{- if not (eq .Values.dns.dns.ipv6Service.udp.type `ClusterIP`) }}
  externalTrafficPolicy: Local
  {{- end }}
  sessionAffinity: ClientIP
  loadBalancerIP: {{ .Values.dns.dns.ipv6Service.tcp.loadBalancerIP }}
  externalIPs:
{{- if .Values.dns.dns.ipv6Service.tcp.externalIPs }}
{{- with .Values.dns.dns.ipv6Service.tcp.externalIPs }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
  ports:
    - port: {{ .Values.dns.dns.ipv6Service.tcp.port }}
      targetPort: {{ .Values.dns.dns.bindPort }}
      protocol: TCP
      name: tcp
    {{- if and .Values.dns.doh.enabled .Values.dns.doh.sidecar }}
    - port: 443
      targetPort: {{ .Values.dns.doh.bindPort }}
      protocol: TCP
      name: https
    {{- end }}
    {{- if and .Values.dns.dot.enabled .Values.dns.dot.sidecar }}
    - port: 853
      targetPort: {{ .Values.dns.dot.bindPort }}
      protocol: TCP
      name: dot
    {{- end }}
  selector:
    {{- include "safesurfer-dns.selectorLabels" . | nindent 4 }}
    app: {{ include "dnsContainerAndAppName" . }}
{{- end }}
{{- end }}
{{- end }}