{{- if .Values.dns.enabled }}
{{- if .Values.dns.dnscrypt.enabled }}
{{- if (not .Values.dns.dnscrypt.useDaemonset) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "name" (dict "Release" .Release "name" "dnscrypt" "nameOverride" .Values.dns.dnscrypt.nameOverride) }}
  namespace: {{ include "ns" (dict "Values" .Values "Release" .Release "IndividualNamespace" .Values.dns.namespace) }}
  labels:
    {{- include "safesurfer-dns.labels" . | nindent 4 }}
{{- if .Values.dns.labels }}
{{- with .Values.dns.labels }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
spec:
  replicas: {{ .Values.dns.dnscrypt.replicas }}
{{- if .Values.dns.dnscrypt.deploymentStrategy }}
  strategy:
{{- with .Values.dns.dnscrypt.deploymentStrategy }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
  selector:
    matchLabels:
      app: {{ include "dnscryptContainerAndAppName" . }}
      {{- include "safesurfer-dns.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "dnscryptContainerAndAppName" . }}
        {{- include "safesurfer-dns.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "safesurfer-dns.dnsdist-pod" . | nindent 6 }}        
{{- end }}
{{- end }}
{{- end }}