{{- if not ((and .Values.testFlags .Values.testFlags.legacyNames)) }}
{{- if .Values.redis.external.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name" (dict "Release" .Release "name" "redis" "nameOverride" .Values.redis.nameOverride) }}-url
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  url: {{ required "Redis external URL must be specified" .Values.redis.external.url | b64enc | quote }}
{{- end }}
{{- end }}