{{- if not ((and .Values.testFlags .Values.testFlags.legacyNames)) }}
{{- if .Values.db.external.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name" (dict "Release" .Release "name" `db` .nameOverride .Values.db.inCluster.nameOverride) }}-login
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: {{ .Values.db.external.pgpassword | b64enc | quote }}
  username: {{ .Values.db.external.pguser | b64enc | quote }}
{{- end }}
{{- end }}