{{- if not ((and .Values.testFlags .Values.testFlags.legacyNames)) }}
{{- range $key, $_ := .Values.providers.ipinfo }}
---
{{- include "ipinfoProviderSecret" (dict "Release" $.Release "Values" $.Values "key" $key "targetNamespace" $.Release.Namespace) }}
{{- end }}
{{- end }}