{{- if not ((and .Values.testFlags .Values.testFlags.legacyNames)) }}
{{- if or .Values.clickhouse.external.enabled .Values.clickhouse.internal.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name" (dict "Release" .Release "name" "clickhouse" "nameOverride" .Values.clickhouse.nameOverride) }}-login
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if .Values.clickhouse.external.enabled }}
  password: {{ .Values.clickhouse.external.connection.password | b64enc | quote }}
  username: {{ .Values.clickhouse.external.connection.username | b64enc | quote }}
  {{- else }}
  password: {{ .Values.clickhouse.internal.password | b64enc | quote }}
  username: {{ .Values.clickhouse.internal.username | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}